language: c


compiler:

  - gcc

before_install:

  - sudo apt-get update

  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev

install:

  - echo  "Reached Install Section"

script:  
  - echo "Reached Script Section"
  - gcc   	Chandan/chandan_practice.c Deepanjali/deepanjali_practice.c Elizabeth/elizabeth_practice.c Gopi/gopi_practice.c Vijay/vijay_practice.c hello_world.c -o output
  - ./output
